cc_test(
    name = "json_scanner_test",
    size = "small",
    srcs = ["json_scanner_test.cpp"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
    cxxopts = ["-std=c++23"]
)
